In [6]:
import pandas as pd

# 예시 DataFrame
data = {'A': [1, 2, 3], 'B': [4, 5, 6]}
df = pd.DataFrame(data)

# 새 열 'C' 추가
df['C'] = df["A"]*3

print(df)
# 새 행 추가 (index 3에 추가)
df.loc[3] = [4, 7, 10]

print(df)


   A  B  C
0  1  4  3
1  2  5  6
2  3  6  9
   A  B   C
0  1  4   3
1  2  5   6
2  3  6   9
3  4  7  10


In [4]:
import pandas as pd

# 두 개의 DataFrame 생성
df1 = pd.DataFrame({'A': [1, 2], 'B': [3, 4]})
df2 = pd.DataFrame({'A': [5, 6], 'C': [7, 8]})

# 두 DataFrame을 수직으로 결합
result = pd.concat([df1, df2], axis=0, ignore_index=True)

print(result)


   A    B    C
0  1  3.0  NaN
1  2  4.0  NaN
2  5  NaN  7.0
3  6  NaN  8.0


In [5]:
df1 = pd.DataFrame({'A': [1, 2]})
df2 = pd.DataFrame({'B': [3, 4]})

result = pd.concat([df1, df2], axis=1)

print(result)


   A  B
0  1  3
1  2  4


In [8]:
import pandas as pd

# DataFrame 생성
df = pd.DataFrame({
    'age': [12, 13, 14, 16],
    'weight': [41.1, 34.5, 83.2, 90.1],
    'height': ['1.72', '1.74', '1.91', '1.54']
})

# DataFrame 정보 확인
print(df.info())


# 'height' 열을 float으로 변환
df['height'] = df['height'].astype(float)

# 'age' 열을 int로 변환
df = df.astype({'age': int})

# DataFrame 정보 확인
print(df.info())
print(df)


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   age     4 non-null      int64  
 1   weight  4 non-null      float64
 2   height  4 non-null      object 
dtypes: float64(1), int64(1), object(1)
memory usage: 228.0+ bytes
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   age     4 non-null      int64  
 1   weight  4 non-null      float64
 2   height  4 non-null      float64
dtypes: float64(2), int64(1)
memory usage: 228.0 bytes
None
   age  weight  height
0   12    41.1    1.72
1   13    34.5    1.74
2   14    83.2    1.91
3   16    90.1    1.54


In [11]:
import pandas as pd
import numpy as np

# 예시 DataFrame 생성
df = pd.DataFrame({
    'age': [12, 13, 14, 16],
    'weight': [41.1, 34.5, np.nan, 90.1],
    'height': ['1.72', '1.74', '1.91', '1.54']
})

# 1. 'weight' 열의 2번째 인덱스에 NaN 값 넣기
df.loc[2, 'weight'] = np.nan

# 2. 1번째 행의 모든 값을 NaN으로 설정
df.loc[1, :] = np.nan
print(df)
# 3. NaN이 있는 행 제거 (기본값은 axis=0, how='any')
df_without_na_any = df.dropna(how='any', axis=0)
print(df_without_na_any)


# 4. NaN이 모두 있는 행만 제거 (how='all')
df_without_na_all = df.dropna(how='all', axis=0)
print(df_without_na_all)


# 5. 최소한 3개의 유효한 값이 있는 행만 남기기
df_without_na_thresh = df.dropna(thresh=3, axis=0)
print(df_without_na_thresh)

# 6. NaN이 하나라도 있는 행 제거 (axis=0)
df_without_na_any_again = df.dropna(how='any', axis=0)
print(df_without_na_any_again)

# 7. NaN이 없으면 해당 행만 남기기 (thresh=df.shape[1]로 설정)
df_without_all_na = df.dropna(thresh=df.shape[1], axis=0)
print(df_without_all_na)

# 8. NaN이 있는 열 제거 (axis=1)
df_without_na_cols = df.dropna(axis=1)
print(df_without_na_cols)

# 9. NaN이 하나라도 있는 열 제거 (axis=1)
df_without_na_cols_any = df.dropna(how='any', axis=1)
print(df_without_na_cols_any)

# 10. NaN이 모두 있는 열 제거 (axis=1)
df_without_na_cols_all = df.dropna(how='all', axis=1)
print(df_without_na_cols_all)

# 11. NaN이 3개 이상이 아닌 열을 제거 (thresh=3)
df.dropna(axis=1, thresh=3, inplace=True)
print(df)


    age  weight height
0  12.0    41.1   1.72
1   NaN     NaN    NaN
2  14.0     NaN   1.91
3  16.0    90.1   1.54
    age  weight height
0  12.0    41.1   1.72
3  16.0    90.1   1.54
    age  weight height
0  12.0    41.1   1.72
2  14.0     NaN   1.91
3  16.0    90.1   1.54
    age  weight height
0  12.0    41.1   1.72
3  16.0    90.1   1.54
    age  weight height
0  12.0    41.1   1.72
3  16.0    90.1   1.54
    age  weight height
0  12.0    41.1   1.72
3  16.0    90.1   1.54
Empty DataFrame
Columns: []
Index: [0, 1, 2, 3]
Empty DataFrame
Columns: []
Index: [0, 1, 2, 3]
    age  weight height
0  12.0    41.1   1.72
1   NaN     NaN    NaN
2  14.0     NaN   1.91
3  16.0    90.1   1.54
    age height
0  12.0   1.72
1   NaN    NaN
2  14.0   1.91
3  16.0   1.54


In [14]:
import pandas as pd

# 데이터 URL
data_url = 'https://andybek.com/pandas-soccer'

# 데이터 읽기
players = pd.read_csv(data_url)

# DataFrame 정보 출력
players.info(verbose=False, memory_usage='deep')

# 각 데이터 타입별 개수
print(players.dtypes.value_counts())


# market_value가 40보다 큰지 확인
print(players.market_value > 40)

# market_value가 40보다 큰 선수들만 필터링
filtered_players = players[players.market_value > 70]
print(filtered_players)

# 필터링된 선수의 수
print(filtered_players.shape)


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 465 entries, 0 to 464
Columns: 17 entries, name to new_signing
dtypes: float64(2), int64(10), object(5)
memory usage: 172.5 KB
int64      10
object      5
float64     2
Name: count, dtype: int64
0       True
1       True
2      False
3      False
4      False
       ...  
460    False
461    False
462    False
463    False
464    False
Name: market_value, Length: 465, dtype: bool
            name               club  age position  position_cat  market_value  \
96   Eden Hazard            Chelsea   26       LW             1          75.0   
267   Paul Pogba  Manchester+United   24       CM             2          75.0   

     page_views  fpl_value fpl_sel  fpl_points  region nationality  \
96         4220       10.5   2.30%         224       2     Belgium   
267        7435        8.0  19.50%         115       2      France   

     new_foreign  age_cat  club_id  big_club  new_signing  
96             0        3        5         1        

In [17]:
players.age.value_counts()
players["age"]

0      28
1      28
2      35
3      28
4      31
       ..
460    21
461    23
462    23
463    21
464    27
Name: age, Length: 465, dtype: int64

In [20]:
import pandas as pd

# 예시 데이터
data_url = 'https://andybek.com/pandas-soccer'
players = pd.read_csv(data_url)

# 1. 고유한 포지션들
print(players.position.unique())
print(players.position.value_counts())

# 2. 고유한 포지션의 개수
print(players.position.unique().size)

# 3. 'LB', 'CB', 'RB'에 해당하는 포지션을 가진 선수들
print(players.position.isin(['LB', 'CB', 'RB']))

# 4. 'LB', 'CB', 'RB' 포지션을 가진 선수들만 필터링
filtered_by_position = players.loc[players.position.isin(['LB', 'CB', 'RB'])]
print(filtered_by_position)

# 5. market_value가 40 이상 50 이하인 선수들
print(players.market_value.between(40, 50))

# 6. market_value가 40 이상 50 이하인 선수들만 필터링
filtered_by_value = players[players.market_value.between(40, 50)]
print(filtered_by_value)

# 7. 나이가 25 이하인 선수들
print(players.age <= 25)

# 8. 나이가 25 이하인 선수들만 필터링
filtered_by_age = players.loc[players.age <= 25]
print(filtered_by_age)


['LW' 'AM' 'GK' 'RW' 'CB' 'RB' 'CF' 'LB' 'DM' 'RM' 'CM' nan 'SS' 'LM']
position
CB    85
CM    63
CF    61
GK    42
DM    37
LW    36
LB    35
RB    34
RW    32
AM    17
LM     8
RM     7
SS     7
Name: count, dtype: int64
14
0      False
1      False
2      False
3      False
4       True
       ...  
460    False
461     True
462     True
463    False
464    False
Name: position, Length: 465, dtype: bool
                  name      club  age position  position_cat  market_value  \
4    Laurent Koscielny   Arsenal   31       CB             3          22.0   
5      Hector Bellerin   Arsenal   22       RB             3          30.0   
7        Nacho Monreal   Arsenal   31       LB             3          13.0   
8     Shkodran Mustafi   Arsenal   25       CB             3          30.0   
17    Gabriel Paulista   Arsenal   26       CB             3          13.0   
..                 ...       ...  ...      ...           ...           ...   
455    Aaron Cresswell  West+Ham   27       

In [21]:
import pandas as pd

# 예시 데이터
data_url = 'https://andybek.com/pandas-soccer'
players = pd.read_csv(data_url)

# 1. 'LB' 포지션, 나이가 25 이하인 선수들
filtered_players_1 = players[
    (players.position == 'LB') &
    (players.age <= 25)
]
print(filtered_players_1)

# 2. 'LB' 포지션, 나이가 25 이하, market_value가 10 이상인 선수들
filtered_players_2 = players[
    (players.position == 'LB') &
    (players.age <= 25) &
    (players.market_value >= 10)
]
print(filtered_players_2)

# 3. 'LB' 포지션, 나이가 25 이하, market_value가 10 이상, 'Tottenham'과 'Arsenal' 클럽이 아닌 선수들
filtered_players_3 = players[
    (players.position == 'LB') &
    (players.age <= 25) &
    (players.market_value >= 10) &
    ~(players.club.isin(['Tottenham', 'Arsenal']))
]
print(filtered_players_3)


                 name               club  age position  position_cat  \
29     Sead Kolasinac            Arsenal   24       LB             3   
54         Brad Smith        Bournemouth   23       LB             3   
112            Kenedy            Chelsea   21       LB             3   
128   Jeffrey Schlupp     Crystal+Palace   24       LB             3   
212      Ben Chilwell     Leicester+City   20       LB             3   
236    Alberto Moreno          Liverpool   25       LB             3   
281         Luke Shaw  Manchester+United   22       LB             3   
294      Paul Dummett   Newcastle+United   25       LB             3   
298  Massadio Haidara   Newcastle+United   24       LB             3   
328      Matt Targett        Southampton   21       LB             3   
354        Josh Tymon         Stoke+City   18       LB             3   
369  Stephen Kingsley            Swansea   22       LB             3   
389        Ben Davies          Tottenham   24       LB          

In [22]:
import pandas as pd

# 예시 데이터
data_url = 'https://andybek.com/pandas-soccer'
players = pd.read_csv(data_url)

# 1. 'Chelsea' 클럽에 소속된 나이가 23 이하인 선수들
chelsea_23under = (players.club == 'Chelsea') & (players.age.le(23))

# 2. 'Chelsea' 클럽에 소속되고 나이가 23 이하인 선수들에서 'position'과 'market_value' 열만 선택
filtered_players_1 = players.loc[chelsea_23under, ['position', 'market_value']]
print(filtered_players_1)

# 3. 열 이름이 'p'로 시작하는 열만 선택
p_cols = players.columns.str.startswith('p')
filtered_players_2 = players.loc[chelsea_23under, p_cols]
print(filtered_players_2)

# 4. 'Chelsea' 클럽에 소속되고 나이가 23 이하인 선수들의 'position' 열만 선택
filtered_players_3 = players.loc[chelsea_23under, 'position']
print(filtered_players_3)

# 5. 0번과 132번 인덱스를 가진 선수들의 'name'과 'market_value' 열 선택
filtered_players_4 = players.loc[[0, 132], ('name', 'market_value')]
print(filtered_players_4)


    position  market_value
110       CF          25.0
111       CB          15.0
112       LB           7.0
115       DM          16.0
    position  position_cat  page_views
110       CF             1        1162
111       CB             3         723
112       LB             3         566
115       DM             2        1011
110    CF
111    CB
112    LB
115    DM
Name: position, dtype: object
               name  market_value
0    Alexis Sanchez          65.0
132  Connor Wickham           6.0


In [23]:
p_cols

array([False, False, False,  True,  True, False,  True, False, False,
       False, False, False, False, False, False, False, False])

In [24]:
import pandas as pd

# 예시 데이터
data_url = 'https://andybek.com/pandas-soccer'
players = pd.read_csv(data_url)

# 1. 중복된 행 확인
duplicates = players.duplicated()
print(duplicates)

# 2. 중복된 행만 선택
duplicates_rows = players[players.duplicated()]
print(duplicates_rows)

# 3. 특정 열에 대한 중복 행 확인
duplicate_specific_columns = players.loc[players.duplicated(subset=['club', 'age', 'position', 'market_value'])]
print(duplicate_specific_columns)

# 4. 중복된 행의 개수
duplicate_count = players.loc[players.duplicated(subset=['club', 'age', 'position', 'market_value'])].shape
print(duplicate_count)

# 5. 마지막 중복 행만 선택
last_duplicates = players.loc[players.duplicated(subset=['club', 'age', 'position', 'market_value'], keep='last')]
print(last_duplicates)

# 6. 모든 중복 행 선택
all_duplicates = players.loc[players.duplicated(subset=['club', 'age', 'position', 'market_value'], keep=False)]
print(all_duplicates)

# 7. 중복된 행 삭제 (첫 번째 유지)
players_no_duplicates = players.drop_duplicates(keep='first')
print(players_no_duplicates)

# 8. 특정 행 삭제 (19번 인덱스)
players_dropped_row = players.drop(labels=19, axis=0)
print(players_dropped_row)

# 9. 여러 행 삭제
players_dropped_rows = players.drop(index=[19, 20, 21, 231, 10])
print(players_dropped_rows)

# 10. 특정 열 삭제
players_dropped_columns = players.drop(labels=['age', 'market_value'], axis='columns')
print(players_dropped_columns)

# 11. 여러 열 삭제
players_dropped_columns_2 = players.drop(columns=['age', 'market_value', 'name'])
print(players_dropped_columns_2)


0      False
1      False
2      False
3      False
4      False
       ...  
460    False
461    False
462    False
463    False
464    False
Length: 465, dtype: bool
                       name     club  age position  position_cat  \
11             Granit Xhaka  Arsenal   24       DM             2   
13  Alex Oxlade-Chamberlain  Arsenal   23       RM             2   
23  Alex Oxlade-Chamberlain  Arsenal   23       RM             2   

    market_value  page_views  fpl_value fpl_sel  fpl_points  region  \
11          35.0        1815        5.5   2.00%          85       2   
13          22.0        1519        6.0   1.80%          83       1   
23          22.0        1519        6.0   1.80%          83       1   

    nationality  new_foreign  age_cat  club_id  big_club  new_signing  
11  Switzerland            0        2        1         1            0  
13      England            0        2        1         1            0  
23      England            0        2        1         1  

In [25]:
import pandas as pd
import numpy as np

# 예시 데이터
data_url = 'https://andybek.com/pandas-soccer'
players = pd.read_csv(data_url)

# 1. 'age'와 'position_cat' 열에 대해 평균값 구하기
agg_mean = players[["age", "position_cat"]].agg('mean')
print(agg_mean)

# 2. 'new_signing' 열에 대해 평균값 구하기
new_signing_mean = players.new_signing.mean()
print(new_signing_mean)

# 3. 'age'와 'position_cat' 열에 대해 최솟값 구하기
agg_min = players[["age", "position_cat"]].agg(np.min)
print(agg_min)

# 4. 숫자형 데이터의 최솟값 구하기
min_values = players.select_dtypes(np.number).agg(np.min)
print(min_values)

# 5. 숫자형 데이터에 대해 'min', 'max', 'mean'을 동시에 구하기
min_max_mean = players.select_dtypes(np.number).agg(['min', 'max', 'mean'])
print(min_max_mean)

# 6. 'market_value'와 'fpl_value' 열에 대해 0.91을 곱한 값 변환
transformed_values = players.loc[:, ['market_value', 'fpl_value']].transform(lambda x: x * 0.91)
print(transformed_values)

# 7. 'market_value'와 'fpl_value' 열에 대해 0.91을 곱한 값 계산
scaled_values = players.loc[:, ['market_value', 'fpl_value']] * 0.91
print(scaled_values)


age             26.776344
position_cat     2.178495
dtype: float64
0.14408602150537633
age             17
position_cat     1
dtype: int64
age             17.00
position_cat     1.00
market_value     0.05
page_views       3.00
fpl_value        4.00
fpl_points       0.00
region           1.00
new_foreign      0.00
age_cat          1.00
club_id          1.00
big_club         0.00
new_signing      0.00
dtype: float64
            age  position_cat  market_value   page_views  fpl_value  \
min   17.000000      1.000000      0.050000     3.000000   4.000000   
max   38.000000      4.000000     75.000000  7664.000000  12.500000   
mean  26.776344      2.178495     11.125649   771.546237   5.450538   

      fpl_points    region  new_foreign   age_cat    club_id  big_club  \
min     0.000000  1.000000     0.000000  1.000000   1.000000  0.000000   
max   264.000000  4.000000     1.000000  6.000000  20.000000  1.000000   
mean   57.544086  1.989247     0.034409  3.195699  10.253763  0.309677   

 

/tmp/ipython-input-3357975461.py:17: FutureWarning: The provided callable <function min at 0x7d39e89300e0> is currently using DataFrame.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  agg_min = players[["age", "position_cat"]].agg(np.min)
/tmp/ipython-input-3357975461.py:21: FutureWarning: The provided callable <function min at 0x7d39e89300e0> is currently using DataFrame.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  min_values = players.select_dtypes(np.number).agg(np.min)


In [28]:
import numpy as np
import pandas as pd

# 예시 데이터 생성
data = {
    'age': [25.5, 30.2, 22.8, 29.9, 40.4],
    'height': [1.75, 1.80, 1.65, 1.72, 1.80],
    'club': ['ClubA', 'ClubB', 'ClubA', 'ClubC', 'ClubB']
}

players = pd.DataFrame(data)

# round_floats 함수 정의
def round_floats(x):
    if x.dtype == np.float64:
        return round(x)  # float64 타입일 경우 반올림
    return x  # 그 외의 경우 그대로 반환

# 1. apply를 사용하여 모든 열에 대해 round_floats 적용
rounded_players = players.apply(round_floats)

# 2. float64 타입의 열을 선택하여 head 출력
float64_columns_head = players.select_dtypes(np.float64).head()

# 3. float64 타입 열에만 apply로 round_floats 적용 후 head 출력
rounded_float64_columns_head = players.select_dtypes(np.float64).apply(round_floats).head()

# 결과 확인
print("Original DataFrame with rounded values:\n", rounded_players)
print("\nFirst 5 rows of float64 columns:\n", float64_columns_head)
print("\nFirst 5 rows after rounding float64 columns:\n", rounded_float64_columns_head)


Original DataFrame with rounded values:
     age  height   club
0  26.0     2.0  ClubA
1  30.0     2.0  ClubB
2  23.0     2.0  ClubA
3  30.0     2.0  ClubC
4  40.0     2.0  ClubB

First 5 rows of float64 columns:
     age  height
0  25.5    1.75
1  30.2    1.80
2  22.8    1.65
3  29.9    1.72
4  40.4    1.80

First 5 rows after rounding float64 columns:
     age  height
0  26.0     2.0
1  30.0     2.0
2  23.0     2.0
3  30.0     2.0
4  40.0     2.0


In [27]:
rounded_players

age  height   club
0  26.0     2.0  ClubA
1  30.0     2.0  ClubB
2  23.0     2.0  ClubA
3  30.0     2.0  ClubC
4  40.0     2.0  ClubB

In [34]:
import numpy as np
a = np.array([9, 5, 7, 6, 8])
a
a.size
a.shape
a.ndim

1

In [36]:
b = np.array([[9, 5, 7, 6, 8],[1,2,3,4,5]])
b
b.size
b.shape
b.ndim

2

In [42]:
b.size
b.ndim
type(b)


numpy.ndarray

In [45]:
b[:,2:4]

array([[7, 6],
       [3, 4]])

In [46]:
import numpy as np

# 1-dimensonal array (벡터)
a1 = np.array([1, 2, 3])

# 2-dimensional array (행렬)
a2 = np.array([[1, 2.0, 3.3],
               [4, 5, 6.5]])

# 3-dimensional array (3D 배열)
a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
               [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]]])

# 1D 배열 특성
print(a1.shape, a1.ndim, a1.dtype, a1.size, type(a1))

# 2D 배열 특성
print(a2.shape, a2.ndim, a2.dtype, a2.size, type(a2))

# 3D 배열 특성
print(a3.shape, a3.ndim, a3.dtype, a3.size, type(a3))


(3,) 1 int64 3 <class 'numpy.ndarray'>
(2, 3) 2 float64 6 <class 'numpy.ndarray'>
(2, 3, 3) 3 int64 18 <class 'numpy.ndarray'>


In [51]:
np.mean(a)
np.min(a)

np.int64(5)

In [60]:
x=np.array([0, np.pi/2])
x
np.sin(x)
np.cos(x)
np.tanh(x)
np.exp(x)
np.log(x)

/tmp/ipython-input-2408252426.py:7: RuntimeWarning: divide by zero encountered in log
  np.log(x)


array([      -inf, 0.45158271])

In [69]:
np.sum(a2,axis=1)
np.std(a1)

np.float64(0.816496580927726)

In [72]:
a1
min(a1)
np.argmin(a1)

np.int64(0)

In [77]:
a2.T
a3.reshape(3,3,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]]])